##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Sun Mar 01 12:53:13 GMT+07:00 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target (series / version approach)
######################################
# Default target series/version (override from command line)
TARGET_SERIES = STM32F407
TARGET_VERSION = VE



######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F103C8)
	BUILD_DIR = build_F103C8
else ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F103C6)
	BUILD_DIR = build_F103C6
else ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F407VE)
	BUILD_DIR = build_F407VE
else ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F411VE)
	BUILD_DIR = build_F411VE
else ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F411CE)
	BUILD_DIR = build_F411CE
else ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F411RE)
	BUILD_DIR = build_F411RE
else ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F429ZI)
	BUILD_DIR = build_F429ZI
else ifeq ($(TARGET_SERIES)$(TARGET_VERSION), STM32F446RE)
	BUILD_DIR = build_F446RE
else
	BUILD_DIR = build
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/motor_control.c \
Core/Src/telemetry_uart.c \
Core/Src/protocol.c \
Core/Src/ringbuf.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Core/Src/system_stm32f4xx.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c

# system and syscall sources are provided by $(SYS) per-target variable
# system and syscall sources are provided by $(SYS) per-target variable# system and syscall sources are provided by $(SYS) per-target variable
######################################
# selecting source (per series)
######################################
ifeq ($(TARGET_SERIES), STM32F103)
	SYS = Core/Src/system_stm32f1xx.c \ Core/Src/syscalls.c \ Core/Src/sysmem.c
	ASM = STMDevices/STM32F103C8Tx/startup_stm32f103xb.s
	CMSIS_INC_DEV = Drivers/CMSIS/Device/ST/STM32F1xx/Include
	CMSIS_INC_UNIT = Drivers/CMSIS/Device/ST/STM32F1xx/Include/STM32f103xB
	LD = STMDevices/STM32F103C8Tx/STM32F103C8Tx_FLASH.ld
	DEF = STM32F103xB
	MCPU = cortex-m3
	MFPU = NONE
	TRGT_CFG = stm32f1x
else ifeq ($(TARGET_SERIES), STM32F407)
	SYS = Core/Src/system_stm32f4xx.c \ Core/Src/syscalls.c \ Core/Src/sysmem.c
	ASM = startup_stm32f407xx.s
	CMSIS_INC_DEV = Drivers/CMSIS/Device/ST/STM32F4xx/Include
	CMSIS_INC_UNIT = Drivers/CMSIS/Device/ST/STM32F4xx/Include
	LD = STM32F407XX_FLASH.ld
	DEF = STM32F407xx
	MCPU = cortex-m4
	MFPU = fpv4-sp-d16
	TRGT_CFG = stm32f4x
else ifeq ($(TARGET_SERIES), STM32F411)
	SYS = Core/Src/system_stm32f4xx.c \ Core/Src/syscalls.c \ Core/Src/sysmem.c
	ASM = STMDevices/STM32F411xe/startup_stm32f411xe.s
	CMSIS_INC_DEV = Drivers/CMSIS/Device/ST/STM32F4xx/Include
	CMSIS_INC_UNIT = Drivers/CMSIS/Device/ST/STM32F4xx/Include/STM32F411xE
	LD = STMDevices/STM32F411xe/STM32F411VETx_FLASH.ld
	DEF = STM32F411xE
	MCPU = cortex-m4
	MFPU = fpv4-sp-d16
	TRGT_CFG = stm32f4x
else ifeq ($(TARGET_SERIES), STM32F429)
	SYS = Core/Src/system_stm32f4xx.c \ Core/Src/syscalls.c \ Core/Src/sysmem.c
	ASM = STMDevices/STM32F429xx/startup_stm32f429xx.s
	CMSIS_INC_DEV = Drivers/CMSIS/Device/ST/STM32F4xx/Include
	CMSIS_INC_UNIT = Drivers/CMSIS/Device/ST/STM32F4xx/Include/STM32F429xx
	LD = STMDevices/STM32F429xx/STM32F429ZITx_FLASH.ld
	DEF = STM32F429xx
	MCPU = cortex-m4
	MFPU = fpv4-sp-d16
	TRGT_CFG = stm32f4x
else ifeq ($(TARGET_SERIES), STM32F446)
	SYS = Core/Src/system_stm32f4xx.c \ Core/Src/syscalls.c \ Core/Src/sysmem.c
	ASM = STMDevices/STM32F446xx/startup_stm32f446xx.s
	CMSIS_INC_DEV = Drivers/CMSIS/Device/ST/STM32F4xx/Include
	CMSIS_INC_UNIT = Drivers/CMSIS/Device/ST/STM32F4xx/Include/STM32F446xx
	LD = STMDevices/STM32F446xx/STM32F446RETx_FLASH.ld
	DEF = STM32F446xx
	MCPU = cortex-m4
	MFPU = fpv4-sp-d16
	TRGT_CFG = stm32f4x
endif

# ASM sources
ASM_SOURCES =  \
$(ASM)

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-D$(DEF) \
-DSTM32F407xx


# AS includes
AS_INCLUDES = 

# CMSIS common include path
CMSIS_INC = Drivers/CMSIS/Include

# C includes
C_INCLUDES =  \
-I Core/Inc \
-I Drivers/STM32F4xx_HAL_Driver/Inc \
-I Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-I $(CMSIS_INC_DEV) \
-I $(CMSIS_INC) \
-I $(CMSIS_INC_UNIT) \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
# Change output names to include series/version
OUTNAME = $(TARGET_SERIES)$(TARGET_VERSION)

LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(OUTNAME).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(OUTNAME).elf $(BUILD_DIR)/$(OUTNAME).hex $(BUILD_DIR)/$(OUTNAME).bin 
	@echo "==========================================="
	@echo "|| The build was completed successfully! ||"
	@echo "==========================================="


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(OUTNAME).elf: $(OBJECTS) Makefile
	@echo "---------------------   SIZE   ----------------------"
	@$(CC) $(OBJECTS) $(LDFLAGS) -o $@  -Wl,--print-memory-usage
	@echo ""
	@$(SZ) $@
	@echo "-----------------------------------------------------"

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@
	
$(BUILD_DIR):
	@cmd /c "if not exist $(BUILD_DIR) mkdir $(BUILD_DIR)"

#######################################
# clean up
#######################################
clean:
	@cmd /c "if exist $(BUILD_DIR) rmdir /S /Q $(BUILD_DIR)"

# -----------------------------------------------------------------
# Flash targets
# - Default `make flash` uses `st-flash` (from stlink tools) to write
#   the generated binary to flash address 0x08000000.
# - If you prefer OpenOCD, use `make flash-openocd` (requires openocd
#   with the correct interface/target config files available).
# -----------------------------------------------------------------

.PHONY: flash flash-openocd

# Tool to use for the simple flash target (override via env: make STLINK=path/to/st-flash flash)
STLINK ?= st-flash
# Default flash address for STM32F4 series
FLASH_ADDR ?= 0x08000000

flash: all
	@echo "Flashing $(BUILD_DIR)/$(OUTNAME).elf using OpenOCD (program, verify, reset)..."
	@openocd -f interface/stlink.cfg -f target/$(TRGT_CFG).cfg -c "program $(BUILD_DIR)/$(OUTNAME).elf verify reset exit"
	@echo "=================================="
	@echo "|| The download was successful! ||"
	@echo "=================================="

# OpenOCD-based flashing (requires valid interface and target cfg files)
flash-openocd: $(BUILD_DIR)/$(OUTNAME).elf
	@echo "Flashing $(BUILD_DIR)/$(OUTNAME).elf using OpenOCD (program, verify, reset)..."
	@openocd -f interface/stlink.cfg -f target/$(TRGT_CFG).cfg -c "program $< verify reset; shutdown"
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
